"""empty message

Revision ID: 65de42fee79a
Revises: e0308bcc55ba
Create Date: 2020-09-23 15:55:18.364284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65de42fee79a'
down_revision = 'e0308bcc55ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tags',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_tags')
    # ### end Alembic commands ###
